// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: deposit_money.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositMoney struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId string  `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount   float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DepositMoney) Reset() {
	*x = DepositMoney{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_money_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoney) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoney) ProtoMessage() {}

func (x *DepositMoney) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_money_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoney.ProtoReflect.Descriptor instead.
func (*DepositMoney) Descriptor() ([]byte, []int) {
	return file_deposit_money_proto_rawDescGZIP(), []int{0}
}

func (x *DepositMoney) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DepositMoney) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositMoneyHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletId string          `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Deposits []*DepositMoney `protobuf:"bytes,2,rep,name=deposits,proto3" json:"deposits,omitempty"`
}

func (x *DepositMoneyHistory) Reset() {
	*x = DepositMoneyHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_deposit_money_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositMoneyHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositMoneyHistory) ProtoMessage() {}

func (x *DepositMoneyHistory) ProtoReflect() protoreflect.Message {
	mi := &file_deposit_money_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositMoneyHistory.ProtoReflect.Descriptor instead.
func (*DepositMoneyHistory) Descriptor() ([]byte, []int) {
	return file_deposit_money_proto_rawDescGZIP(), []int{1}
}

func (x *DepositMoneyHistory) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DepositMoneyHistory) GetDeposits() []*DepositMoney {
	if x != nil {
		return x.Deposits
	}
	return nil
}

var File_deposit_money_proto protoreflect.FileDescriptor

var file_deposit_money_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x43, 0x0a, 0x0c, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x60,
	0x0a, 0x13, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x49, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x08, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x73,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_deposit_money_proto_rawDescOnce sync.Once
	file_deposit_money_proto_rawDescData = file_deposit_money_proto_rawDesc
)

func file_deposit_money_proto_rawDescGZIP() []byte {
	file_deposit_money_proto_rawDescOnce.Do(func() {
		file_deposit_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_deposit_money_proto_rawDescData)
	})
	return file_deposit_money_proto_rawDescData
}

var file_deposit_money_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deposit_money_proto_goTypes = []interface{}{
	(*DepositMoney)(nil),        // 0: pb.DepositMoney
	(*DepositMoneyHistory)(nil), // 1: pb.DepositMoneyHistory
}
var file_deposit_money_proto_depIdxs = []int32{
	0, // 0: pb.DepositMoneyHistory.deposits:type_name -> pb.DepositMoney
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deposit_money_proto_init() }
func file_deposit_money_proto_init() {
	if File_deposit_money_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_deposit_money_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoney); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_deposit_money_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositMoneyHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_deposit_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deposit_money_proto_goTypes,
		DependencyIndexes: file_deposit_money_proto_depIdxs,
		MessageInfos:      file_deposit_money_proto_msgTypes,
	}.Build()
	File_deposit_money_proto = out.File
	file_deposit_money_proto_rawDesc = nil
	file_deposit_money_proto_goTypes = nil
	file_deposit_money_proto_depIdxs = nil
}
